version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    build: .
    environment:
      - CONNECTION_URL=jdbc:postgresql://postgres:5432/mydatabase
      - USER=myuser
      - PASSWORD=mypassword
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:
